### ISSUE TITLE
Spellcheck language preference

### ISSUE THREAD

**Issue by fedelibre** [sonnyp/Commit#105]
I guess that the spellcheck defaults to the system language.

What if a non-english user will use Commit to contribute to an English repository? This dotted red confusion appears :-)

![immagine](https://github.com/sonnyp/Commit/assets/1644647/357a8541-81a5-46ad-b901-ce9a9efabfb7)

May you add a language preference? Or detect the language and always accept English.

Thanks

**Comment by EncryptedEasty** [comment]
@fedelibre

See https://github.com/sonnyp/Commit/pull/98#issuecomment-1743451087 for a potential solution

**Comment by fedelibre** [comment]
Ok, then the setting is available. I'm happy I can disable it.

Switching to English doesn't seem to work now.
I'm on Fedora Silverblue and maybe I don't have the english spellcheck dictionary?

**Comment by fedelibre** [comment]
However, if I disable it and reopen Commit, the spellchecking is active again. My choice is not saved.

Can you make sure that the last choice is kept?

**Comment by fedelibre** [comment]
Ok, I'll close this issue
