### ISSUE TITLE
Make it show previous commits

### ISSUE THREAD

**Issue by llothar** [sonnyp/Commit#12]
Would be nice if it could show the last commits. Sometimes you need to see what you wrote in previous ones. And it would be very nice if the previous commits could be changed as well. 

Thats what i miss when i enter commit "stories".

**Comment by sonnyp** [comment]
Sorry I'm having a hard time understanding the use case.

Why would the message of your current commit be affected by previous commit messages?

What's the benefit over using git rebase interactive?
