### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [sonnyp/Commit#18]
The current icon isn't quite in line with the guidelines, would you like help with a new one?

I took a quick stab at it, how about something like this?

![image](https://user-images.githubusercontent.com/1908896/131034377-e3240aba-8211-40d1-8523-53438791f36e.png)

**Comment by sonnyp** [comment]
Not sure if you mean copyright infringement but the git logo is under CC BY 3.0 https://git-scm.com/downloads/logos 

What about something lighter like this ? I'm open to a different color variant 

![image](https://user-images.githubusercontent.com/19673/131252684-152f8f66-7bd0-4a89-9557-f54f0b214427.png)

![image](https://user-images.githubusercontent.com/19673/131252719-a51b514b-45f2-4ce3-b6c0-4494008cbe1b.png)

**Comment by bertob** [comment]
> Not sure if you mean copyright infringement

I didn't mean legally (though there might be trademarks, not sure?), just in terms of avoiding it looking like something "official" from the git project. Generally you want third party apps to have their own separate visual identities from the underlying service/technology.

> What about something lighter like this

Symbolic + background is a bit too simple for an app icon, ideally it should have some physical depth and detail.

Here's an attempt at making the git shape work without being too close to their branding:

![image](https://user-images.githubusercontent.com/1908896/131264193-29468a82-8cd0-4319-bf95-9354d4ebe0f0.png)

**Comment by sonnyp** [comment]
I love it
