### ISSUE TITLE
Double border on text view

### ISSUE THREAD

**Issue by bertob** [sonnyp/Commit#20]
The text view where the commit message is entered seems to have a double border:

![image](https://user-images.githubusercontent.com/1908896/132264599-928625f0-8125-435a-83e7-6d7b62de6920.png)

It's especially noticeable in high contrast:

![image](https://user-images.githubusercontent.com/1908896/132264617-b8152b9d-76f2-44bd-91cc-3a4f2682e0e7.png)

**Comment by BrainBlasted** [comment]
This is due to using `shadow-type=In` - Glade inserts that by default for ScrolledWindows, causing a double border. I submitted an MR for this on the original app years ago and that never got merged. I'll send another here.
