### ISSUE TITLE
Move preferences

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Commit#24]
> Are more preferences planned? Currently there's a single option in the preferences dialog, which looks a bit weird.

https://gitlab.gnome.org/Teams/Circle/-/issues/83#note_1257600 

For now there will be only one preference. I imagine 1 or 2 more in the future.

I see 2 options

1. Move preferences to this window (maybe at the top with a section named "Preferences")

![Screenshot from 2021-09-12 11-34-44](https://user-images.githubusercontent.com/19673/132982897-6d5a5966-72ef-4bac-ab1e-b740a0e941b5.png)

2. Move preferences to the menu popup of that same window

![Screenshot from 2021-09-12 11-59-43](https://user-images.githubusercontent.com/19673/132983371-daa7acbb-8dfe-4af9-b7a0-8129dc37768e.png)

@bertob do you think the first option makes sense?

**Comment by bertob** [comment]
Hmm yeah, the message length hint is not something people change all the time, so making it part of the initial setup window makes sense to me.

**Comment by sonnyp** [comment]
How about this

![Screenshot from 2021-09-18 14-23-50](https://user-images.githubusercontent.com/19673/133888713-c2467b94-81a1-4258-87ae-3d9487d2bd12.png)

**Comment by bertob** [comment]
Not sure the "Preferences" header is needed if there's just one preference, but otherwise LGTM
