### ISSUE TITLE
Cannot edit previous commits when squashing

### ISSUE THREAD

**Issue by TheEvilSkeleton** [sonnyp/Commit#25]
Whenever I try to squash rebase, I cannot edit the previous commits:

https://user-images.githubusercontent.com/50847364/134078137-d3b95697-065a-4ea5-a3d6-936553993db6.mp4

**Comment by sonnyp** [comment]
That's unfortunate. Commit isn't very smart with comments and consider everything after the first `\n# ` to be a comment. 

Shouldn't be terribly hard to fix but let's do after #30

**Comment by TheEvilSkeleton** [comment]
Thanks.

**Comment by sonnyp** [comment]
https://user-images.githubusercontent.com/19673/149637892-f3373812-2f7e-447f-9d58-b9be51824954.mp4

**Comment by TheEvilSkeleton** [comment]
Looks great!
