### ISSUE TITLE
Add maintainer info for Apps for GNOME

### ISSUE THREAD

**Issue by A6GibKm** [sonnyp/Commit#27]
For the maintainer to appear in Apps for gnome it must contain info about the git forge account

```xml
  <maintainer>
    <foaf:Person>
      <foaf:name>User Name</foaf:name>
      <foaf:mbox rdf:resource="mailto:user-email@emailprovider.org" />
      <gnome:userid>gnome-user-acc</gnome:userid>
      <foaf:account>
        <foaf:OnlineAccount>
            <foaf:accountServiceHomepage rdf:resource="https://github.com/"/>
            <foaf:accountName>user-github-acc</foaf:accountName>
        </foaf:OnlineAccount>
      </foaf:account>
    </foaf:Person>
  </maintainer>
```

**Comment by sonnyp** [comment]
like this https://github.com/sonnyp/Commit/commit/d04d058bb1df842d6aa253d82e1f5d08c21ba537 ?

**Comment by sonnyp** [comment]
Can I specify multiple accounts like so

```
  <maintainer>
    <foaf:Person>
      <foaf:name>Sonny Piers</foaf:name>
      <foaf:mbox rdf:resource="mailto:sonny@fastmail.net" />
      <foaf:account>
        <foaf:OnlineAccount>
            <foaf:accountServiceHomepage rdf:resource="https://github.com/"/>
            <foaf:accountName>sonnyp</foaf:accountName>
        </foaf:OnlineAccount>
        <foaf:OnlineAccount>
          <foaf:accountServiceHomepage rdf:resource="https://gitlab.gnome.org"/>
          <foaf:accountName>sonny</foaf:accountName>
        </foaf:OnlineAccount>
      </foaf:account>
    </foaf:Person>
  </maintainer>
```

**Comment by A6GibKm** [comment]
> like this [d04d058](https://github.com/sonnyp/Commit/commit/d04d058bb1df842d6aa253d82e1f5d08c21ba537) ?

Yup. Thanks.

> Can I specify multiple accounts like so

I am asking.

**Comment by sophie-h** [comment]
Hi again :)

It's a bit ambiguous because I have to use one account to fetch the maintainer info.

But we could just use the first account to fetch name, pronouns, website etc and just link the remaining accounts?

I guess it would be multiple `foaf:account`s:

```xml
  <maintainer>
    <foaf:Person>
      <foaf:name>Sonny Piers</foaf:name>
      <foaf:mbox rdf:resource="mailto:sonny@fastmail.net" />
      <foaf:account>
        <foaf:OnlineAccount>
            <foaf:accountServiceHomepage rdf:resource="https://github.com/"/>
            <foaf:accountName>sonnyp</foaf:accountName>
        </foaf:OnlineAccount>
      <foaf:account>
      </foaf:account>
        <foaf:OnlineAccount>
          <foaf:accountServiceHomepage rdf:resource="https://gitlab.gnome.org"/>
          <foaf:accountName>sonny</foaf:accountName>
        </foaf:OnlineAccount>
      </foaf:account>
    </foaf:Person>
  </maintainer>
```

Currently I'm still trying to figure out why apps.gnome.org isn't picking up the existing doap file :grimacing:

**Comment by sophie-h** [comment]
> Currently I'm still trying to figure out why apps.gnome.org isn't picking up the existing doap file

That's fixed now

**Comment by sonnyp** [comment]
Appears to be fixed. Thanks.

Should I tried adding a second `foaf:account` for Gitlab ?

**Comment by sophie-h** [comment]
Yes, I already tried to ensure that it will not break anything :)

The data will not show up yet, but I will add support in the future. It even makes sense to merge information, since GitHub is lacking a field for pronouns for example.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Commit/commit/ff8bfb9aac8fc26f93f88f03af7115afce51b5e6

Many thanks for apps.gnome.org - really cool initiative - gives a nice, accessible and localized homepage to my apps.
