### ISSUE TITLE
Flat headerbar

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Commit#31]
Depends on https://github.com/sonnyp/Commit/pull/30

Does it make sense for Commit to use a flat header bar? I kinda like the third option.

cc @bertob @BrainBlasted wdyt?

default
![Screenshot from 2021-09-23 18-09-15](https://user-images.githubusercontent.com/19673/134549738-1be18bf2-55a6-4700-8dd2-2d20c954a884.png)

flat

![Screenshot from 2021-09-23 18-09-31](https://user-images.githubusercontent.com/19673/134549733-14979c72-3049-40f1-933a-9fb20424e47c.png)

flat - same color as content

![Screenshot from 2021-09-23 18-49-08](https://user-images.githubusercontent.com/19673/134549967-b24091bf-4f8f-49d4-87c9-309e1df9f213.png)

**Comment by BrainBlasted** [comment]
Imo it does not make sense stylistically. This is a case where you want the dragging point (the headerbar) to be distinct from the content. For flat windows like Solanum the entire window is supposed to be a dragging point.

**Comment by sonnyp** [comment]
Makes sense.

**Comment by bertob** [comment]
Yeah, since the window can scroll I'd keep the distinct headerbar.
