### ISSUE TITLE
run on wayland

### ISSUE THREAD

**Issue by RustPanda** [sonnyp/Commit#46]
"flatpak run --socket=wayland --env=GDK_BACKEND=wayland  --file-forwarding re.sonny.Commit @@"
fedora 35

**Comment by sonnyp** [comment]
What is the problem?

**Comment by RustPanda** [comment]
I installed everything according to the instructions, but nothing worked for me. I am using Fedora 35 + Gnome 41.
Wayland's explicit direction helped.

The problem is that the flat bag out of the box doesn't work. To start it, you have to dance with a tambourine.

**Comment by sonnyp** [comment]
I use Fedora 35 , GNOME 41 and Commit flatpak.

I don't have this problem. Maybe you could share more about what happens - do you get an error message or anything?

**Comment by sonnyp** [comment]
I use Wayland

```
sonny@porygon ~> echo $XDG_SESSION_TYPE
wayland
```

What if you run `flatak run re.sonny.Commit` directly?

**Comment by RustPanda** [comment]
@sonnyp, window opens, no errors

**Comment by sonnyp** [comment]
Interesting - so it only happens when git opens Commit.

I really don't know how to reproduce the problem - it's gonna make it difficult to debug.

How did you install Git?

Is there anything special about your setup you can think of ?

**Comment by RustPanda** [comment]
I installed the git with the command: `$ sudo dnf install git`. I am using [ASUS-TUF-Gaming-FX505DD-DT-DU](https://www.asus.com/ru/Laptops/For-Gaming/TUF-Gaming/ASUS-TUF-Gaming-FX505DD-DT-DU/) laptop purchased in Korea.

**Comment by RustPanda** [comment]
@sonnyp i reinstalled fedora completely but it didn't help

**Comment by sonnyp** [comment]
@RustPanda can you comment on how you solved the problem? Might help others.

**Comment by RustPanda** [comment]
@sonnyp i reinstalled fedora. Works on Fedora 35 and Fedora 36. I did not do anything.

**Comment by mpetuska** [comment]
> @sonnyp May not be using Wayland? Yes, I am getting the error:
> 
> ```shell
> Waiting for your editor to close the file... 
> (re.sonny.Commit:2): Gtk-WARNING **: 12:57:24.606: cannot open display: 
> error: There was a problem with the editor 'flatpak run --file-forwarding re.sonny.Commit @@'.
> Please supply the message using either -m or -F option.
> ```
> 
> Adding `--env=GDK_BACKEND=wayland` helped me

Had exactly the same problem on F36@Wayland. The env var indeed fixed an issue for me. Note that I initiaally installed fedora 35 and then upgraded to 36 as opposed to fresh 36 install (might be related).
