### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [sonnyp/Commit#51]
https://hosted.weblate.org/projects/commit/commit/#information is GPLv3-only
It should however be GPLv3-or-later,
as per
https://github.com/sonnyp/Commit/blob/9e012379a3db19703299ccd1356411feafe2c2bc/README.md#license

It can be changed in https://hosted.weblate.org/settings/commit/commit

**Comment by comradekingu** [comment]
Top stuff.

**Comment by sonnyp** [comment]
Fixed. 

Thank you.

 Edit: If you add Norwegian Bokmål nb_NO I can translate that.
 
 You can add yourself - there is a "Start new translation" button at the bottom of https://hosted.weblate.org/projects/commit/commit/

**Comment by comradekingu** [comment]
@sonnyp 
It is grayed out. I think the setting is "Add new translation" almost at the bottom of
https://hosted.weblate.org/settings/commit/commit/#files

**Comment by sonnyp** [comment]
It's already the right setting.

![Screenshot from 2022-01-08 12-25-43](https://user-images.githubusercontent.com/19673/148642381-c87a2349-01ea-4a1e-aa27-10be2888e264.png)

> It is grayed out.

Could it be that you're not signed in ?

**Comment by sonnyp** [comment]
try this https://hosted.weblate.org/new-lang/commit/commit/

**Comment by comradekingu** [comment]
@sonnyp Let's pretend that wasn't the issue, but it is fixed X)
