### ISSUE TITLE
Insert hard newlines instead of wrapping long lines

### ISSUE THREAD

**Issue by ebassi** [sonnyp/Commit#52]
Commit should not put the entire commit message on as few lines as possible: it makes reading commit messages harder than necessary on the command line.

If the user specifies a hard limit for the length of each line, the commit message should be following that size. This should be possible by iterating over the text using Pango, and finding where words wrap.

**Comment by sonnyp** [comment]
Nice to see you here / on Commit :) 

> If the user specifies a hard limit for the length of each line

Not sure if you're talking about the current setting but there is no hard limit - just a "hint" for the subject line. The goal is not to wrap but to help the user knowing when it exceeds the max length on Github/Gitlab/... 

See https://robertcooper.me/post/git-commit-messages#subject-line-less-than-or-equal-to-72-characters-in-length

What you are talking about would be a new setting for https://robertcooper.me/post/git-commit-messages#body-line-length-limited-to-80-characters correct ?

If so - here is what I can do
* Clarify what the current limit is about
* Add a new setting for commit body max line length

**Comment by ebassi** [comment]
> What you are talking about would be a new setting for https://robertcooper.me/post/git-commit-messages#body-line-length-limited-to-80-characters correct ?

Yes. Basically, right now the commit message is just wrapped in the UI by the text input; the underlying content is a single line. While some people do use this style, it's kind of broken on the CLI. Additionally, it messes up any formatting.

> * Clarify what the current limit is about

It would probably help; I mostly gleaned it was about the commit subject because it was set to 50 characters, but it's not overly clear.

> * Add a new setting for commit body max line length

This would, indeed, be the thing I'm asking.

**Comment by sonnyp** [comment]
> This should be possible by iterating over the text using Pango, and finding where words wrap.

Could you elaborate a little or link to documentation / example?

**Comment by bilelmoussaoui** [comment]
I came here to report the same issue, I got tricked by the small window until I noticed the very long line commit on gitlab

**Comment by sonnyp** [comment]
@bilelmoussaoui any chance you can share that commit url - I want to make sure we are talking about the same thing

**Comment by bilelmoussaoui** [comment]
Sure, see https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2317/diffs?commit_id=61f3c6bbc2b2f0341a83525d3e2985f9b444f1c8

**Comment by sonnyp** [comment]
After playing around with TextView/Pango I realized that given the commit body is only text - it should be fine to present a different wrapping than what commit ends up saving so I've done that in https://github.com/sonnyp/Commit/commit/bd733c633b94c3b8560737782de99c080302539f

I opened this issue has a follow up https://github.com/sonnyp/Commit/issues/57 for slightly better UX.

**Comment by sonnyp** [comment]
Fixed in v3.1.0

Please let me know how it works for you.

If the window is smaller than the requested wrap width (72) then Commit will soft wrap at 72 on save.

If the window is bigger, wrap is disabled and a ruler / right margn is displayed

![Screenshot from 2022-03-20 10-38-39](https://user-images.githubusercontent.com/19673/159186392-ce290852-73f3-4998-a677-ca5329af7d7c.png)


![Screenshot from 2022-03-20 11-16-45](https://user-images.githubusercontent.com/19673/159186375-d6104c1e-2420-4086-98fc-7f91d0bd6294.png)
