### ISSUE TITLE
Weblate translations locked

### ISSUE THREAD

**Issue by milotype** [sonnyp/Commit#53]
@comradekingu Just to inform you that translations on Weblate are currently locked. Maybe it's on purpose, maybe not ;-)

**Comment by sonnyp** [comment]
Thanks for the heads up and sorry for the late reply.

Fixed the issue and unlocked.

**Comment by pervoj** [comment]
@sonnyp I would like to update the Czech translation, but it's still locked for me

**Comment by milotype** [comment]
The languages are still locked!

**Comment by sonnyp** [comment]
Unlocked

**Comment by milotype** [comment]
@sonnyp Croatian translation finished
