### ISSUE TITLE
Rounded bottom corners (using HdyWindow)

### ISSUE THREAD

**Issue by bertob** [sonnyp/Commit#6]
All the cool kids are doing it :P

**Comment by sonnyp** [comment]
Nice - I was just looking at libhandy for the frist time for `HdyPreferencesWindow`.

Anything else ?

**Comment by sonnyp** [comment]
![Screenshot from 2021-05-04 21-22-55](https://user-images.githubusercontent.com/19673/117058904-7dbc0e80-ad1f-11eb-8c1e-aae273c74903.png)

This is with `HdyApplicationWindow` and `HdyHeaderBar`

I don't know if it's any different than before but it feels like the text could use 1pt spacing on the left (window border) and top (header bar) - WDYT ?

**Comment by bertob** [comment]
> I don't know if it's any different than before but it feels like the text could use 1pt spacing on the left (window border) and top (header bar) - WDYT ?

Agreed, I'd go even further and try 6px or something :P 

However, that only makes sense if the padding is within the scrollview, and the text is not prematurely cut off at the top when scrolling.

**Comment by sonnyp** [comment]
Here is with 6px padding

![Screenshot from 2021-05-06 10-47-07](https://user-images.githubusercontent.com/19673/117894750-50da9f00-b2bd-11eb-8005-5cb5f6b9d3a3.png)

LGTM - WDYT?

> However, that only makes sense if the padding is within the scrollview, and the text is not prematurely cut off at the top when scrolling.

You mean like this:

![Screenshot from 2021-05-06 19-55-09](https://user-images.githubusercontent.com/19673/117894761-5506bc80-b2bd-11eb-924f-6244727a6ed7.png)

?

**Comment by bertob** [comment]
Yeah, this looks great!
