### ISSUE TITLE
Title auto-capitalization is very unconvenient with Convential Commits

### ISSUE THREAD

**Issue by liferooter** [sonnyp/Commit#61]
Auto-capitalization is very unconvenient with [Convential Commits](https://www.conventionalcommits.org/en/v1.0.0/) because it uses lowercase prefixes. I suggest to make auto-capitalization optional.

**Comment by liferooter** [comment]
Wow, it really works! Thank you for such cool feature!

**Comment by sonnyp** [comment]
You're very welcome :) 

Don't hesitate if you have feedback on it or anything else.

Thanks you for Text Pieces which I use often.

**Comment by sonnyp** [comment]
Related: https://github.com/sonnyp/Commit/issues/62
