### ISSUE TITLE
Do not auto capitalize when amending

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Commit#62]
Related https://github.com/sonnyp/Commit/issues/61

When amending/rewording a commit - the first letter is capitalized. 

And maybe capialize first letter only after first whitespace to avoid https://github.com/sonnyp/Commit/issues/61

**Comment by melix99** [comment]
> maybe capialize first letter only after first whitespace to avoid #61

The same thing as in #61 just happened to me right now. I was fighting with the capitalized letter without realizing that I needed to type the `:`, so I guess this is a better idea :)
