### ISSUE TITLE
Issues editing `~/.gitconfig`

### ISSUE THREAD

**Issue by markochk** [sonnyp/Commit#65]
1. in terminal, run `git config --global core.editor "flatpak run --file-forwarding re.sonny.Commit @@"`
2. in terminal, run `git config --global -e`. It'll open the Commit window and print this message in terminal:
```
hint: Waiting for your editor to close the file... Warning: unknown commit type encountered in: /run/user/1000/doc/ab12bc58/.gitconfig
```
3. pressing `Abort` will delete all contents in .gitconfig, leaving the user with an empty file
4. however, if I don't abort and try to make some changes to `.gitconfig`, I'm unable to as existing content is read-only, and I'm only able to insert content at the start of the file or append it at the end of the file

**Comment by sonnyp** [comment]
Fixed in the next release.

I also added syntax highlighting for gitconfig/hgrc

![Screenshot from 2022-04-18 23-33-37](https://user-images.githubusercontent.com/19673/163881929-60d11ae9-bc4a-430c-9a76-3a0a9370f2f9.png)
