### ISSUE TITLE
Bad contrast for highlight in dark mode 

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Commit#69]
![image](https://user-images.githubusercontent.com/19673/164895390-83c7e9c2-955e-4e8a-b53c-48e9c7018c43.png)

I'm also not a big fan of the yellow, maybe we should use previous colors :

![screenshot](https://user-images.githubusercontent.com/19673/164896539-0becdef4-00c8-4a0c-af1e-2aea39d566af.png)

**Comment by sonnyp** [comment]
@bertob thoughts?

**Comment by bertob** [comment]
No super strong opinion, the yellow could work if it's semitransparent.

**Comment by sonnyp** [comment]
semitransparent `yellow_1` didn't look too god

I went with `puple_5` https://floss.social/@sonny/108684471643896514
