### ISSUE TITLE
Don't auto uppercase first letter

### ISSUE THREAD

**Issue by bilelmoussaoui** [sonnyp/Commit#70]
Currently whenever I update a commit message, the application auto uppercase the first letter which is not really a desired behaviour. Would it be possible to completely disable that or at least make it optional?

**Comment by Cogitri** [comment]
Still happens for me w/ 3.2.0


https://user-images.githubusercontent.com/8766773/166425077-7fb390d9-d192-4ed5-838a-4b3ed571ea69.mp4

**Comment by fmuellner** [comment]
> That should be fixed with the latest release, could you try updating?

The behavior has definitively improved (thanks for that!), but the prefix is still occasionally auto-uppercased when amending. I'm afraid I don't have a reliable reproducer.

**Comment by sonnyp** [comment]
Thanks @Cogitri - I have been able to reproduce the problem thanks to your screencast.

Fixed in https://github.com/sonnyp/Commit/commit/593193f646e1499912c730315b594935344e0194 - will make a release shortly.

Happy GUADEC!

**Comment by Cogitri** [comment]
Thanks :)
