### ISSUE TITLE
Not triggered by 'git commit'

### ISSUE THREAD

**Issue by yochananmarqos** [sonnyp/Commit#8]
Continuing from [Reddit](https://www.reddit.com/r/gnome/comments/n4kgzi/commit_message_editor_gitmercurial/gwxwgy8?utm_source=share&utm_medium=web2x&context=3)...

[PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/blob/master/commit/PKGBUILD)

Installed files:

```
❯ pacman -Ql commit
commit /usr/
commit /usr/bin/
commit /usr/bin/re.sonny.Commit
commit /usr/share/
commit /usr/share/appdata/
commit /usr/share/appdata/re.sonny.Commit.appdata.xml
commit /usr/share/applications/
commit /usr/share/applications/re.sonny.Commit.desktop
commit /usr/share/glib-2.0/
commit /usr/share/glib-2.0/schemas/
commit /usr/share/glib-2.0/schemas/re.sonny.Commit.gschema.xml
commit /usr/share/icons/
commit /usr/share/icons/hicolor/
commit /usr/share/icons/hicolor/scalable/
commit /usr/share/icons/hicolor/scalable/apps/
commit /usr/share/icons/hicolor/scalable/apps/re.sonny.Commit.svg
commit /usr/share/re.sonny.Commit/
commit /usr/share/re.sonny.Commit/about.js
commit /usr/share/re.sonny.Commit/application.css
commit /usr/share/re.sonny.Commit/application.js
commit /usr/share/re.sonny.Commit/editor.js
commit /usr/share/re.sonny.Commit/main.js
commit /usr/share/re.sonny.Commit/meson.build
commit /usr/share/re.sonny.Commit/re.sonny.Commit
commit /usr/share/re.sonny.Commit/scm.js
commit /usr/share/re.sonny.Commit/setup.js
commit /usr/share/re.sonny.Commit/util.js
commit /usr/share/re.sonny.Commit/validateCommitButton.js
commit /usr/share/re.sonny.Commit/welcome.js
commit /usr/share/re.sonny.Commit/welcome.ui
commit /usr/share/re.sonny.Commit/window.js
commit /usr/share/re.sonny.Commit/window.ui
```

```
❯ git --version
git version 2.31.1
```

The output of `git commit` complains if there's nothing to commit or commits as expected.

**Comment by sonnyp** [comment]
Right - you'd have to have something to commit for your git editor to popup.

What about

```
git clone git@github.com:sonnyp/Commit.git
cd Commit
touch foo.txt
git add foo.txt
git commit
```

?

**Comment by yochananmarqos** [comment]
That works. Earlier, in my pkgbuilds directory for my repo linked above, it was not. I just tested again now and it worked. I can't explain why it's working now and wasn't before.

**Comment by sonnyp** [comment]
Good to hear.

The instructions should add a way to test somehow and make it clearer when commit will popup.

**Comment by yochananmarqos** [comment]
I suppose you could clarify in the `README`, but I understood what I needed to do, it just didn't work at first. I also had been trying to get Gnomit to work before, so I already understood what this was.

**Comment by yochananmarqos** [comment]
I see you submitted `gnomit` to the AUR, do you want to add `commit` yourself? Since you're the developer, I bet you could submit a merge request and merge `gnomit` into it.

**Comment by sonnyp** [comment]
I'm not really interested in submitting PKGBUILD for the time being. Let me know if you do submit, and I'll mention it in the README.

I saw that you also have a Tangram PKGBUILD - I can update the Tangram README as well if you'd like to submit it.

**Comment by yochananmarqos** [comment]
I just added `commit` to the AUR.

I hadn't submitted Tangram because there's already another project with the same name [already there](https://aur.archlinux.org/packages/tangram). Maybe call it `tangram-messenger` or something?

**Comment by sonnyp** [comment]
I would suggest `tangram-app`, `tangram-gtk` or `tangram-gnome` instead.

**Comment by sonnyp** [comment]
Many thanks for submitting commit to aur .

I mentioned it in the README https://github.com/sonnyp/commit/#installation let me know if you'd like me to change something.

A few suggestions

Optional dependencies
  * git (git support)
  * mercurial (mercurial support)
  * gspell (Spell-checking support)

Dependencies: gtk3 and glib2

**Comment by yochananmarqos** [comment]
> I would suggest tangram-app, tangram-gtk or tangram-gnome instead.

I guess I was thinking of Telegram when I said `tangram-messenger`. 😂️

> Dependencies: gtk3 and glib2

What about `gjs` and `libhandy`?

**Comment by sonnyp** [comment]
> What about gjs and libhandy?

Right `gjs` as well

libhandy will be required for the next version

If you want to be super thorough I guess `ninja` and `gettext` could be added to make dependencies. Your `PKGBUILD` might be used as a reference for other packages, so it might be useful.

**Comment by yochananmarqos** [comment]
`gettext` is part of the `base-devel` group and is not necessary to add to makedepends(). `ninja` is pulled in by `meson`. I've [updated the dependencies](https://aur.archlinux.org/cgit/aur.git/commit/?h=commit&id=241431e611221b96d9ffa65f10eef5518c54184d).

**Comment by yochananmarqos** [comment]
What about `tangram-web`?

**Comment by sonnyp** [comment]
`tangram-web` :+1:

**Comment by yochananmarqos** [comment]
Just added it: [`tangram-web`](https://aur.archlinux.org/packages/tangram-web/)

**Comment by sonnyp** [comment]
@yochananmarqos many thanks https://github.com/sonnyp/tangram#installation

If you have a feature request or annoyance with Commit or Tangram please let me know - I'd be happy to have a look.

**Comment by sonnyp** [comment]
Actually Tangram used to be published as `tangram` on AUR.

Not sure how it got replaced so easily but digital and printed magazine out there still refer to it; for example https://www.linux-magazine.com/Issues/2020/235/Tangram `yay -S tangram`

It also breaks repology https://repology.org/project/tangram/versions

Any chance we can get the name back?

I guess aur should start accepting  reverse dns names `re.sonny.Tangram` to avoid this issues...

**Comment by yochananmarqos** [comment]
Oh, that's right. You had [`gigagram-git`](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=gigagram-git) and created [`tangram`](https://aur.archlinux.org/cgit/aur.git/commit/?h=tangram&id=8f28eb5d7ec7cbb74ed06e490a5bc858822f397f) when the project name changed. Why was it deleted? The current `tangram` package was able to be added since the original was gone.

We could request to merge `tangram-web` into `tangram`, but then the current `tangram` would have to be resubmitted with a different name.

**Comment by sonnyp** [comment]
> Why was it deleted?

No idea - I sure didn't :/

**Comment by yochananmarqos** [comment]
Oh, you must've orphaned it then. The new maintainer then updated with the different project.

**Comment by sonnyp** [comment]
Right - I didn't think a new maintainer would do such thing - anything we can do about it ?

**Comment by sonnyp** [comment]
I have contacted the maintainer of https://aur.archlinux.org/packages/tangram/ - let's see.

**Comment by sonnyp** [comment]
I received no replied, so I sent an orphan request.

```
sonny [1] filed an orphan request for tangram [2]:

The current maintainer of the package has replaced the package with
his own software.

It is causing issues as instructions to install tangram from AUR
exists in the wild - including in paper magazine.

We would like this package to be orphaned so that the maintainer of
tangram-web can reinstate the original purpose of this aur package.

I got in touch with them with the following email but received no
answer so far.


Hello David,

My name is Sonny, I'm the author of Tangram
https://github.com/sonnyp/tangram and the original submitter to the
AUR package https://aur.archlinux.org/packages/tangram/ .

I stopped using Arch Linux and hoped that someone would step in to
maintain the AUR package. Someone has but couldn't use the tangram
package anymore so they published it under tangram-web
https://aur.archlinux.org/packages/tangram-web/

Unfortunately this is causing issues as instructions to install
Tangram through AUR still exists in the wild, including in printed
paper magazine such as Linux magazine, for example https://www.linux-
magazine.com/Issues/2020/235/Tangram "yay -S tangram".

I would be really grateful if you would publish your application on
aur under a different name and allow the maintainer of tangram-web to
take over ownership of tangram .

Cheers!

[1] https://aur.archlinux.org/account/sonny/
[2] https://aur.archlinux.org/pkgbase/tangram/
```

**Comment by sonnyp** [comment]
We have finally regained ownership of https://aur.archlinux.org/packages/tangram/

I added you as co-maintainer and will disown the package once I'm confident David will not regain ownership.

Could you re-publish tangram-web under tangram?

**Comment by yochananmarqos** [comment]
I've restored `tangram` and submitted a request to merge `tangram-web` into `tangram`. You can update your README with the original package.

You can disown it and I'll be the Maintainer, David cannot reclaim it.

**Comment by sonnyp** [comment]
On behalf of users, thank you!

https://github.com/sonnyp/tangram#installation
