### ISSUE TITLE
Confirm or save commit message when "escape" is pressed

### ISSUE THREAD

**Issue by mitchhentges** [sonnyp/Commit#88]
First, thanks for the great app! It's very well done :grin: 

Only one thing is bugging me: once in a while, my muscle memory hits the "escape" key when I'm done typing my commit message (maybe because I'm used to Jetbrains IDEs and that puts my cursor back in the main editing panel? Unsure why). Unfortunately, with this Commit app, it cancels the commit and throws away my message, which hurts my feelings :pensive: 

I have two potential behaviour suggestions that could help with this sharp edge:
1. If the message text field has been modified, show a "confirm" dialog if the user tries to abort. This is a simple solution, but it can cause "confirmation fatigue" where people are annoyed by it and start to ignore it, so I trust your judgement here, however you lean.
2. A more complex solution could be to save the in-progress message to disk if the commit is canceled out. Then, on the user's next commit, re-use that last message that they had before. Perhaps the "message re-use" could even be conditional based on whether it's the same repository. I _think_ this is the more ergonomic solution, but I'm interested in your thoughts.

Thanks again, and I hope you have a good holiday season :wave:

**Comment by sonnyp** [comment]
Glad you like it.

> A more complex solution

It's not viable to save the message for later. It just won't work with Git.

> If the message text field has been modified, show a "confirm" dialog if the user tries to abort. 

I guess you're unlikely to abort after taking the time to edit the commit message, so this may be a good idea. 

I can review a PR

Something like:

---

Are you sure you want to abort?
It will discard the message and cancel the commit
- [ ] Don't warn me again.

---
